-- Create table hostal_audit
CREATE TABLE IF NOT EXISTS public.hostal_audit (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id bigint not null,
  action text not null, -- INSERT, UPDATE, DELETE
  old_data jsonb,
  new_data jsonb,
  user_id uuid, -- O text, dependiendo de como manejen auth. Si es anonimo, null.
  created_at timestamptz not null default now()
);

-- Index for faster querying by table and record
CREATE INDEX IF NOT EXISTS idx_audit_table_record ON public.hostal_audit(table_name, record_id);
