-- Create table hostal_users
CREATE TABLE IF NOT EXISTS public.hostal_users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  role text not null, -- admin, recepcion, aseo, mantencion
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Opcional: Insertar un usuario admin por defecto si la tabla esta vacia
INSERT INTO public.hostal_users (full_name, email, role)
SELECT 'Admin Inicial', 'admin@hostal.com', 'admin'
WHERE NOT EXISTS (SELECT 1 FROM public.hostal_users);
